apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gjpd6gvl7-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:0904f24d35c64e26de12e45d96c93635f158867d@sha256:4ded97a5cdabe7dbde3dd6f8b463935e570b1a99b0419aaa0f1807dd16187b7e
          name: container-image
